import * as z from "zod";

export const CRTSubmissionSchema = z.object({
    model: z.string(),
    brand: z.string(),
    manufacturer: z.string().optional(),
    author: z.string().optional(),
    series: z.string().optional(),
    screenSize: z.string(),
    inputs: z.string().optional(),
    supportedResolutions: z.string().optional(),
    formats: z.string().optional(),
    aspectRatio: z.string(),
    tubeMake: z.string().optional(),
    chassis: z.string().optional(),
    audio: z.string().optional(),
    purpose: z.string().optional(),
    yearLaunched: z.number().optional(),
    yearDiscontinued: z.number().optional(),
    weight: z.string().optional(),
    physicalSize: z.string().optional(),
    degaussingType: z.string().optional(),
    assemblyCountry: z.string().optional(),
    physicalDescription: z.string(),
    operationalDescription: z.string().optional(),
    serviceManualLink: z.string().optional(),
    ownersManualLink: z.string().optional(),
    summary: z.string(),
    similarMakesAndModels: z.string().optional(),
    originalRemoteMakeAndModel: z.string().optional(),
})

